using EPPlusSamples.WorkbookWorksheetAndRanges;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EPPlusSamples
{
    public static class WorkbookWorksheetAndRangesSamples
    {
        public static async Task RunAsync()
        {
            // Sample 1.1 - Simply creates a new workbook from scratch
            // containing a worksheet that adds a few numbers together 
            CreateASimpleWorkbook.Run();

            // Sample 1.2 - Simply reads some values from the file generated by sample 1
            // and outputs them to the console
            ReadWorkbookSample.Run();

            //Sample 1.3 - Load and save using async methods
            await UsingAsyncAwaitSample.RunAsync();

            //Sample 1.4 - Copy, Fill and Sort Ranges
            CopyFillAndSort.Run();

            //Sample 1.5 - Notes/Comments and Threaded comments
            CommentsSample.Run();

            // Sample 1.6 - creates a workbook from scratch 
            //Shows how to use Ranges, Styling, Namedstyles and Hyperlinks
            SalesReportFromDatabase.Run();

            //Sample 1.7
            //This sample shows the performance capabilities of the component and shows sheet protection.
            //Load X(param 2) rows with five columns
            PerformanceAndProtectionSample.Run(65534);

            //Sample 1.8 - Linq
            //Opens Sample 1.7 and perform some Linq queries
            ReadDataUsingLinq.Run();

            //Sample 1.9 - Add references to external workbooks
            ExternalLinksSample.Run();

            //Sample 1.10 - Ignore cell errors using the IngnoreErrors Collection
            IgnoreErrorsSample.Run();
        }
    }
}
